#
# Docker file for libmo tests
#

FROM ubuntu:16.04

# prepare
RUN apt-get update -qq

# install build essentials
RUN apt-get install -yq git build-essential clang

# install dependencies
RUN apt-get install -yq --no-install-recommends \
    autoconf-archive \
    gnome-common \
    gobject-introspection \
    gtk-doc-tools \
    language-pack-de-base \
    libglib2.0-dev

# build & install the current Git snapshot of mo
RUN mkdir /build

WORKDIR /build
