language: c

sudo: required
dist: xenial

services:
  - docker

compiler:
  - clang
  - gcc

before_script:
  - docker build -t mo -f test/ci/Dockerfile .

script: docker run -t -e CC=$CC -v $(pwd):/build mo ./test/ci/build.sh
