language: c

sudo: required
dist: xenial

services:
  - docker

compiler:
  - clang
  - gcc

env:
  - BUILD=autotools
  - BUILD=meson

before_script:
  - docker build -t mo -f test/ci/Dockerfile-$BUILD .

script: docker run -t -e BUILD=$BUILD -e CC=$CC -v $(pwd):/build mo ./test/ci/build-$BUILD.sh
